#160451558 implement login functionality
andela/lotus-ah-frontend pull request #10
Opened 2018-11-06 22:18 UTC by Mrshinezee

#### What does this PR do?
 - Implementing login functionality

#### Description of Task to be completed?
- a user should be able to log in

#### How should this be manually tested?
- start the app by running ```yarn start:dev```
the app should open on port ```8080``` on your browser
navigate to the login page

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
[#160451558](https://www.pivotaltracker.com/story/show/160451558, "Users should be able to Login to Authors Haven")

#### Screenshots (if appropriate)
<img width="528" alt="screen shot 2018-11-06 at 10 57 38 pm" src="https://user-images.githubusercontent.com/20081126/48097215-82201300-e219-11e8-8453-bbd599bf921a.png">

#### Questions:

2018-11-07 08:05 UTC, e0works approved these changes
Nice job @Mrshinezee 
It looks good

2018-11-07 08:57 UTC, obulaworld requested changes
Please attend to the changes below

2018-11-07 08:57 UTC, obulaworld commented on src/styles/_signup.scss
> +/* rgba(242,242,242,.9) */
Plus put new line here

2018-11-07 08:57 UTC, obulaworld commented on src/styles/_signupMixin.scss
> +}
Please also put a new line here

2018-11-07 08:57 UTC, obulaworld commented on src/styles/_update.scss
> +}
Please delete this file or include a new line

2018-11-07 08:57 UTC, obulaworld commented on src/styles/loader.scss
> +
Please this file is using pure css, we should rather convert it scss codes

2018-11-07 09:38 UTC, obulaworld approved these changes
Looking Good to Me

2018-11-07 10:57 UTC, mindsworth approved these changes
kindly Implement review

2018-11-07 10:57 UTC, mindsworth commented on src/containers/Login/Login.jsx
> +  }
Looking good

But we can do away with class `constructor()` for the react componet inheritance and the `bind()` of events in our components for a cleaner and readable codes. Try to configure babel plugins using @babel/plugin-proposal-class-properties

```
  constructor(props) {
    super(props);
    this.state = {
      email: '',
      password: ''
    };
    this.onChange = this.onChange.bind(this);
    this.onSubmit = this.onSubmit.bind(this);
  }
```

2018-11-07 12:21 UTC, KaiserPhemi requested changes
@Mrshinezee 
Implement feedback.

2018-11-07 12:21 UTC, KaiserPhemi commented on src/components/AuthenticatedRoute.jsx
>  const AuthenticatedRoute = ({ component: Component, ...rest }) => (
#### Nitpick
Reformat this into
```js
const AuthenticatedRoute = ({ component: Component, ...rest }) => (
  <Route 
    {...rest}
    render={
      props => (
        Auth.verifyUserToken(
          localStorage.getItem('authorsHavenAuthToken'))
          ? <Component {...props}/>
          : <Redirect 
            to={{
              pathname: '/login',
              state: { from: props.location }
            }}
          />
      )}
  />
);
```

2018-11-07 12:21 UTC, KaiserPhemi commented on src/components/Router.jsx
>  /**
#### Nitpick
Add a blank line before this to separate it from the `history` defined above

2018-11-07 12:21 UTC, KaiserPhemi commented on src/containers/Login/Login.jsx
> +  render() {
##### Critical
Take note of the above warning.
<img width="724" alt="screen shot 2018-11-07 at 1 03 23 pm" src="https://user-images.githubusercontent.com/26272628/48130631-900f7b80-e28d-11e8-92a0-d6c762624eb7.png">

##### Tips
Consider refactoring part of this into a separate component then import that component here. e.g. the `form` part can be made into a separate component.

2018-11-07 12:21 UTC, KaiserPhemi commented on src/containers/Login/Login.jsx
> +  login: (detail) => {
#### Critical
This can be refactored into a one-liner i.e.
```js
login: detail => dispatch(userLoginRequest(detail))
```

2018-11-07 12:21 UTC, KaiserPhemi commented on src/containers/Login/__test__/login.test.js
> +    const wrapper = shallow(<Provider store={store}><Login /></Provider>);
#### Nitpick
Reformat into:
```js
const wrapper = shallow(
  <Provider store={store}>
    <Login />
  </Provider>
);
```

2018-11-07 12:21 UTC, KaiserPhemi commented on src/index.js
>  // import bootstrap
#### Nitpick
Add comment `// styles` not `// import bootstrap`. Also line `14` falls under this category as well

2018-11-07 12:21 UTC, KaiserPhemi commented on src/index.js
> +import { authenticateUser, logOutUser } from './action/auth';
#### Nitpick
Add comment `// actions`

2018-11-07 12:21 UTC, KaiserPhemi commented on src/reducers/auth.js
> +import initialState from '../store/initialState';
#### Critical
Comment each imports properly. i.e. `state`, `reducer`, `action types`

2018-11-07 12:21 UTC, KaiserPhemi commented on src/styles/_variables.scss
> +// color variables
#### Nitpick
One comment is ok.

2018-11-07 15:55 UTC, KaiserPhemi commented on src/components/Login/LoginForm.jsx
> +export default LoginForm;
#### Nitpick 
Add a new line here

2018-11-08 03:19 UTC, KaiserPhemi approved these changes

2018-11-08 03:19 UTC, merged