#161676743 User Logout Feature
andela/lotus-ah-frontend pull request #12
Opened 2018-11-08 11:09 UTC by obulaworld

#### What does this PR do?
 - Implemented the logout feature

#### Description of Task to be completed?
- a user should be able to log out of the application

#### How should this be manually tested?
- start the app by running ```yarn start:dev```
the app should open on port ```8080``` on your browser
navigate to the login page, login as a user then use the logout 
link to log out of the app

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
[#161676743](https://www.pivotaltracker.com/story/show/161676743, "Users should be able to Logout of Authors Haven")

#### Screenshots (if appropriate)

#### Questions:

2018-11-08 11:46 UTC, andela-phemmy approved these changes
Looking Good To Me. Nice Work.

2018-11-08 11:47 UTC, Mrshinezee requested changes

2018-11-08 11:47 UTC, Mrshinezee commented on src/components/Logout/Logout.jsx
> +  console.log(props);
Please, remove the console.log

2018-11-08 11:47 UTC, Mrshinezee commented on src/components/Logout/__test__/logout.test.js
> +import Logout from '../Logout';
comment with
//components

//state

2018-11-08 11:47 UTC, Mrshinezee commented on src/components/Logout/__test__/logout.test.js
> +    const wrapper = shallow(<Provider store={store}><Logout /></Provider>);
You can break it down to
<Provider store={store}>
<Logout />
</Provider>

2018-11-08 11:51 UTC, Mrshinezee requested changes

2018-11-08 11:51 UTC, Mrshinezee commented on src/components/Logout/Logout.jsx
> +  logout: () => {
You can make a one line
```logout: () => dispatch(logOutUser())```

2018-11-09 09:45 UTC, KaiserPhemi approved these changes

2018-11-09 09:46 UTC, merged