#160451557 Reset Password Functionality
andela/lotus-ah-frontend pull request #15
Opened 2018-11-13 12:20 UTC by andela-phemmy

#### What does this PR do?
     This PR implements Reset/Forgot password functionality
#### Description of Task to be completed?
      1. Configure the resetReducer
      2. Configure the reset action and add action type
      3. Add containers and components
      4. Test reducers, actions and components
#### How should this be manually tested?
      On localhost
        1. start the app on port `8080`
        2. Navigate to sign in
        3. Click on forgot password
        4. input your password 
        5. An email will be sent to you, click on reset password
        6. input password and confirm password
        7. proceed to reset your password
#### Any background context you want to provide?
        N/A
### What are the relevant pivotal tracker stories?
       #160451557
#### Screenshots (if appropriate)
<img width="1680" alt="screen shot 2018-11-13 at 1 13 36 pm" src="https://user-images.githubusercontent.com/43237059/48413042-b712f500-e746-11e8-9312-d373bc13b0e7.png">
<img width="1680" alt="screen shot 2018-11-13 at 1 13 49 pm" src="https://user-images.githubusercontent.com/43237059/48413050-c2662080-e746-11e8-85e5-4c6cd578529b.png">
<img width="1680" alt="screen shot 2018-11-13 at 1 13 58 pm" src="https://user-images.githubusercontent.com/43237059/48413066-cf830f80-e746-11e8-87d3-c18d63523347.png">
<img width="1680" alt="screen shot 2018-11-13 at 1 14 16 pm" src="https://user-images.githubusercontent.com/43237059/48413076-dc9ffe80-e746-11e8-8a50-270268be7ab8.png">

#### Questions:
        N/A

2018-11-13 22:09 UTC, e0works requested changes

2018-11-13 22:09 UTC, e0works commented on .eslintrc
> +  }
You forgot to add a new line at the end of this file, please update the file

2018-11-13 22:09 UTC, e0works commented on .prettierrc
> + }
Please, add a new line here also

2018-11-13 22:09 UTC, e0works commented on src/components/ForgotPassword/ForgotPassword.jsx
> +import PropTypes from 'prop-types';
Please, comment appropriately
prop-types and redux are not part of React library
it should read

```js
        // react libraries
        import React, { Component } from 'react';

        // tthird-party libraries
        import PropTypes from 'prop-types';
	import { connect } from 'react-redux';
```

2018-11-13 22:09 UTC, e0works commented on src/components/ForgotPassword/ForgotPasswordForm.jsx
> +import PropTypes from 'prop-types';
Here also, give a space between lines 2 and 3 and comment the imports properly

```js
// third-party libraries
import PropTypes from 'prop-types';
```

2018-11-13 22:09 UTC, e0works commented on src/components/ResetPassword/ResetPasswordForm.jsx
> +import PropTypes from 'prop-types';
separate  ***prop-types*** from **react** library

2018-11-13 22:09 UTC, Victor-Ugwueze commented on src/components/login/LoginForm.jsx
>  import React, { Component, Fragment } from 'react';
comment on the imports here

2018-11-13 22:09 UTC, Victor-Ugwueze commented on src/components/reusables/Loader.jsx
> +import React, { Component } from 'react';
Add comment on the import statements here

2018-11-13 22:09 UTC, Victor-Ugwueze commented on src/index.html
>    <meta charset="UTF-8">
I don't think we are making use of this file, so it should be deleted

2018-11-14 08:29 UTC, Mrshinezee requested changes

2018-11-14 08:29 UTC, Mrshinezee commented on .eslintrc
> +
add new line

2018-11-14 08:29 UTC, Mrshinezee commented on .prettierrc
> +
add a new line

2018-11-14 09:35 UTC, e0works approved these changes

2018-11-14 11:55 UTC, Mrshinezee approved these changes
LGTM

2018-11-14 14:02 UTC, KaiserPhemi requested changes
@andela-phemmy 
Rebase.

2018-11-14 15:15 UTC, KaiserPhemi approved these changes

2018-11-14 15:15 UTC, merged