#160451559 Implement Social Authentication
andela/lotus-ah-frontend pull request #16
Opened 2018-11-14 11:17 UTC by andela-phemmy

#### What does this PR do?
     This PR implements Social authentication functionality
#### Description of Task to be completed?
      1. Add environment variables for social auth URLs
      2. Add social auth href to all social auth buttons
      3. Test SocialSignIn, LoginTypeSelectors and LoginType components
#### How should this be manually tested?
      On localhost
        1. start the app on port `8080`
        2. Navigate to sign in
        3. Click on any social auth button
        4. Or navigate to sign up
        5. Click on any social auth button
        6. In any of the above cases, you will be redirected to the social auth page
        7. Authenticate with your credentials and proceed to landing page 
#### Any background context you want to provide?
        N/A
### What are the relevant pivotal tracker stories?
       #160451559
#### Screenshots (if appropriate)
<img width="1680" alt="screen shot 2018-11-14 at 12 15 42 pm" src="https://user-images.githubusercontent.com/43237059/48479240-0c164000-e807-11e8-86b6-edb607c2395b.png">

#### Questions:
        N/A

2018-11-14 12:21 UTC, e0works requested changes

2018-11-14 12:21 UTC, e0works commented on .prettierrc
> +
You forgot to add a new line, here

2018-11-14 12:21 UTC, e0works commented on src/action/resetPasswordAction.js
> +// constants importation
I think this comment should read
```js
// action types
```

2018-11-14 12:21 UTC, e0works commented on src/components/SocialLogin/SocialSignIn.jsx
> +import React, { Fragment } from 'react';
Please, document the Component `SocialSignIn`
also put a comment on the react library importation

2018-11-14 12:21 UTC, e0works commented on src/components/__tests__/forgot.test.js
> +// react and react-redux libraries
I think you should separate this 2 and 3.
It should read

```js
// react libraries
import React from 'react';

// third-party libraries
import { Provider } from 'react-redux';
import Enzyme, { shallow } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
```

2018-11-14 12:21 UTC, e0works commented on src/components/__tests__/reset.test.js
> +// react libraries
Please comment on the imports properly
react-redux is not part of react library

2018-11-14 13:45 UTC, e0works approved these changes

2018-11-14 22:10 UTC, KaiserPhemi requested changes
@andela-phemmy 
Implement feedback.

2018-11-14 22:10 UTC, KaiserPhemi commented on src/components/SocialLogin/SocialSignIn.jsx
> +        <a href={process.env.FACEBOOK_URL}>
#### Critical
You could extract all the urls once and just pass them at the anchor tags i.e:
```js
const { // needed props } = process.env;
```

2018-11-14 22:10 UTC, KaiserPhemi commented on src/components/__tests__/loginType.test.js
> +Enzyme.configure({ adapter: new Adapter() });
#### Critical
Refactor this i.e. the `enzyme` setup should go into a file e.g. `testSetup` file then add the key to your `jest` configuration in `package.json`.

Also, do this for all the test files.

For more clarity check [Using `enzyme` with React16](https://airbnb.io/enzyme/docs/installation/react-16.html) and [`enzyme` setup](https://stackoverflow.com/questions/46627353/where-should-the-enzyme-setup-file-be-written)

2018-11-14 22:10 UTC, KaiserPhemi commented on src/components/login/LoginTypeSelector.jsx
> +            href={process.env.FACEBOOK_URL}
#### Critical
Same as above. Extract the urls from the global env object first.

2018-11-15 16:47 UTC, KaiserPhemi approved these changes

2018-11-15 16:47 UTC, merged