#160451571 users should be able to view notifications
andela/lotus-ah-frontend pull request #19
Opened 2018-11-16 15:03 UTC by Victor-Ugwueze

#### What does this PR do?

#### Description of Task to be completed?
- write action tests for notifications
- get user unread notifications when authenticated
- mark a single notification as read
- mark all notifications as read

#### How should this be manually tested?
- start the app
- you should see all your notification after you are authenticated
- click on each notification item to clear or
- click on `mark all as read` to clear all

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
[#160451571](https://www.pivotaltracker.com/story/show/160451571, "view user notification")

#### Screenshots (if appropriate)
<img width="1680" alt="screen shot 2018-11-16 at 3 16 04 pm" src="https://user-images.githubusercontent.com/24890605/48628911-9d78e400-e9b8-11e8-927c-9fb4188f15e8.png">

#### Questions:

2018-11-17 06:21 UTC, KaiserPhemi requested changes

2018-11-17 06:21 UTC, KaiserPhemi commented on src/action/notification/__test__/getNotification.js
> +// action
#### Nitpick
There should only be one blank line between this line and previous one above it

2018-11-17 06:21 UTC, KaiserPhemi commented on src/components/fixtures/notification/NotificationAction.jsx
> +
#### Nitpick
What are you doing with all these blank lines?

2018-11-17 06:21 UTC, KaiserPhemi commented on src/components/fixtures/notification/NotificationAction.jsx
> +// action
#### Nitpick
What's this comment solving for?

2018-11-17 06:21 UTC, KaiserPhemi commented on src/components/reusables/dropdown/notificationDropdown/_NotificationDropdown.scss
> +}
#### Nitpick
Add a new line here.

2018-11-17 06:21 UTC, KaiserPhemi commented on src/containers/article/CreateArticle.jsx
>  const mapStateToProps = (state = {}) => ({
#### Critical
Why are you passing an empty state here?

2018-11-17 06:21 UTC, KaiserPhemi commented on src/containers/LandingPage/LandingPage.jsx
> +const mapDispatchToProps = dispatch => ({
#### Critical
You can refactor this. i.e.
```js
const mapDispatchToProps = {
  markNotificationAsRead(token, id, mark) { markNotificationAsReadAction(token, id, mark); }
}
```
You can check [here](https://daveceddia.com/redux-mapdispatchtoprops-object-form/) for clarity

2018-11-17 06:21 UTC, KaiserPhemi commented on src/components/reusables/dropdown/notificationDropdown/NotificationDropdown.jsx
> +import NotificationItem from '../../notification/NotificationItem';
#### Critical
This should have it's own comment 
i.e. 
```js
// component
```

2018-11-17 06:21 UTC, KaiserPhemi commented on src/components/reusables/dropdown/menuDropdown/Dropdown.jsx
> +  const menuArray = [
#### Critical
Drop this into a fixture file and call it within the component.

2018-11-20 17:39 UTC, obulaworld approved these changes
Looking Good to Me

2018-11-20 18:24 UTC, andela-phemmy approved these changes
Implement the feedbacks. Looking Good to Me

2018-11-22 21:56 UTC, Victor-Ugwueze commented on src/containers/LandingPage/LandingPage.jsx
> +const mapDispatchToProps = dispatch => ({
I have gone through the article, this what I saw as a sample code
```js
const mapDispatchToProps = {
  decrement,
  increment: () => increment(42),
  reset
};
```

If I use it this way,

## 1
```js
const mapDispatchToProps = {
  markNotificationAsRead(token, id, mark) { markNotificationAsReadAction(token, id, mark); }
}
````
it throws error

So, I have to write this way for it to work 
## 2
```js
const mapDispatchToProps = {
  markNotificationAsRead: (token, id, mark) => markNotificationAsReadAction(token, id, mark) 
}
````
I haven't been able to make it work number one

2018-11-22 22:33 UTC, Victor-Ugwueze commented on src/components/reusables/dropdown/notificationDropdown/NotificationDropdown.jsx
> +import NotificationItem from '../../notification/NotificationItem';
I have implemented this feedback

2018-11-23 08:59 UTC, KaiserPhemi approved these changes

2018-11-23 09:01 UTC, merged