#160451563 User should be able to rate an article
andela/lotus-ah-frontend pull request #22
Opened 2018-11-21 15:05 UTC by Mrshinezee

#### What does this PR do?
A user should be able to rate an article

#### Description of Task to be completed?
implement a functionality that allows user rate an article

#### How should this be manually tested?
- start the app
- select an article to view
- on the view article page, a rating icon will be available
- click on the icon to rate

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
[#160451571](https://www.pivotaltracker.com/story/show/160451563, "Users should be able to rate articles")

#### Screenshots (if appropriate)
<img width="1437" alt="screen shot 2018-11-21 at 3 56 43 pm" src="https://user-images.githubusercontent.com/20081126/48849452-af86c800-eda6-11e8-81f5-12fe4e2d03bc.png">

#### Questions:

2018-11-21 15:38 UTC, e0works requested changes
Nice job @Mrshinezee

2018-11-21 15:38 UTC, Victor-Ugwueze commented on src/components/reusables/reaction/Rating.jsx
> +import RadialProgress from '../radialProgress/RadialProgress';
RadialProgress should be commented as 
```js
// components
import RadialProgress from '../radialProgress/RadialProgress';
```

2018-11-21 15:38 UTC, Victor-Ugwueze commented on src/components/article/viewArticle/ViewArticlePage.jsx
>      const shareUrl = `https://lotus-ah-staging.herokuapp.com/api/v1${this.props.location.pathname}`;
please change this line

```js
const shareUrl = `https://lotus-ah-staging.herokuapp.com/api/v1${this.props.location.pathname}`;
```
to 
```js
const shareUrl = `https://lotus-ah-frontend.herokuapp.com/api/v1${this.props.location.pathname}`;
```

2018-11-21 15:38 UTC, Victor-Ugwueze commented on src/reducers/article/__test__/rateArticle.test.js
> +
please add a new line here

2018-11-21 16:04 UTC, koiic approved these changes
Looks good to me

2018-11-21 16:05 UTC, e0works approved these changes

2018-11-22 10:58 UTC, KaiserPhemi commented
@Mrshinezee 
Rebase.

2018-11-22 14:14 UTC, merged