#160451577 Article Report
andela/lotus-ah-frontend pull request #28
Opened 2018-11-27 08:18 UTC by obulaworld

#### What does this PR do?
A user should be able to report an article

#### Description of Task to be completed?
- implement a functionality that allows a user to report an article
- Build out the report reducers to handle state update

#### How should this be manually tested?
- start the app
- select an article to view
- on the view article page, a report button is available
- click on the button, a modal will appear
- enter the reason for the report and click submit report

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
[#160451577](https://www.pivotaltracker.com/story/show/160451577, "Users should be able to report an article")

#### Screenshots (if appropriate)

<img width="711" alt="screen shot 2018-11-27 at 9 11 28 am" src="https://user-images.githubusercontent.com/20061324/49067722-17b13000-f225-11e8-8c30-e3683d9d747a.png">

#### Questions:

2018-11-27 09:32 UTC, mindsworth approved these changes
Looking good to me...

2018-11-27 09:32 UTC, mindsworth commented on src/components/reusables/userDetail/_userDetail.scss
> +}
Please add a new line here

2018-11-27 11:57 UTC, KaiserPhemi requested changes
#### Nitpick
Please implement feedback

2018-11-27 12:07 UTC, obulaworld commented on src/components/reusables/userDetail/_userDetail.scss
> +}
Implemented. Thanks

2018-11-27 17:02 UTC, KaiserPhemi requested changes
@obulaworld 
#### Critical 
Please rebase

2018-11-27 19:40 UTC, KaiserPhemi requested changes
@obulaworld 
Please rebase

2018-11-28 21:05 UTC, KaiserPhemi approved these changes

2018-11-28 21:05 UTC, merged